id = "samurai"
name = "Samurai Theme"
version = "0.2.0"
schema_version = 1
description = "A wesleydmscn.com theme created by wesleydmscn"
repository = "https://github.com/wesleydmscn/zed-samurai-theme"
authors = ["wesleydmscn"]
themes = ["samurai.json"]
icon_themes = []
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
